"""Content-free provider usage normalization. Proxy copy is generated by sync-usage.py."""
from datetime import datetime, timezone

PRICING_VERSION = 'google-standard-2026-09-17'
INTRO_END = 1798761600  # 2027-01-01 UTC; unknown future prices must not look free.
PRICES = {
    'gemini-3.8-flash': (.75, .075, 3.75),
    'gemini-3.6-flash': (1.50, .15, 7.50),
    'gemini-3.7-flash': (.75, .075, 3.75),
    'gemini-3.5-flash-lite': (.30, .03, 2.50),
    'gemini-3-flash-preview': (.50, .05, 3.00),
}


def _count(value):
    return value if isinstance(value, int) and not isinstance(value, bool) and value >= 0 else None


def normalize(usage):
    usage = usage if isinstance(usage, dict) else {}
    native = 'promptTokenCount' in usage or 'candidatesTokenCount' in usage
    prompt = _count(usage.get('promptTokenCount' if native else 'prompt_tokens'))
    output = _count(usage.get('candidatesTokenCount' if native else 'completion_tokens'))
    details = usage.get('completion_tokens_details')
    details = details if isinstance(details, dict) else {}
    input_details = usage.get('prompt_tokens_details')
    input_details = input_details if isinstance(input_details, dict) else {}
    thoughts = _count(usage.get('thoughtsTokenCount', 0) if native else details.get('reasoning_tokens'))
    cached = _count(usage.get('cachedContentTokenCount', 0) if native else
                    input_details.get('cached_tokens'))
    if cached is not None and (prompt is None or cached > prompt):
        cached = None
    billed = (output + thoughts if output is not None and thoughts is not None else None) if native else output
    if native and billed is None:
        total = _count(usage.get('totalTokenCount'))
        if total is not None and prompt is not None and total >= prompt:
            billed = total - prompt
            if thoughts is not None and thoughts <= billed:
                output = billed - thoughts
    visible = output if native else (output - thoughts if output is not None and thoughts is not None
                                     and thoughts <= output else None)
    return {'input_tokens': prompt, 'cached_input_tokens': cached, 'visible_output_tokens': visible,
            'reasoning_tokens': thoughts, 'billed_output_tokens': billed,
            'usage_completeness': 'complete' if None not in (prompt, cached, billed) else 'partial' if usage else 'unknown'}


def estimate(model, counts, created=None):
    created = datetime.now(timezone.utc).timestamp() if created is None else created
    prices = PRICES.get(model)
    if not prices or created >= INTRO_END or counts.get('usage_completeness') != 'complete':
        return None
    prompt, cached = counts['input_tokens'], counts['cached_input_tokens']
    return ((prompt - cached) * prices[0] + cached * prices[1]
            + counts['billed_output_tokens'] * prices[2]) / 1_000_000


def estimate_range(model, counts, created=None):
    """Token-only bounds when compatible APIs omit cache details; never label the upper bound exact."""
    created = datetime.now(timezone.utc).timestamp() if created is None else created
    prices = PRICES.get(model)
    prompt, output = counts.get('input_tokens'), counts.get('billed_output_tokens')
    if not prices or created >= INTRO_END or prompt is None or output is None:
        return None
    exact = estimate(model, counts, created)
    if exact is not None:
        return {'lower': exact, 'upper': exact, 'basis': 'reported_cache'}
    return {'lower': (prompt * min(prices[:2]) + output * prices[2]) / 1_000_000,
            'upper': (prompt * max(prices[:2]) + output * prices[2]) / 1_000_000,
            'basis': 'cache_unknown'}
